feat: switch to bitnami repository
kubernetes-sigs/minibroker pull request #121
Opened 2021-01-08 22:58 UTC by f0rmiga

Fixes #118.

2021-01-09 00:51 UTC, mook-as requested changes

2021-01-09 00:51 UTC, mook-as commented on pkg/minibroker/minibroker.go
> -func loadInClusterClient() kubernetes.Interface {
FWIW, we could have passed both clients back instead. (Not an issue to inline it, of course.)

2021-01-09 00:51 UTC, mook-as commented on pkg/minibroker/minibroker.go
> +		}
Does something like this work?
```suggestion
		dr := c.dynamicClient.Resource(r.Mapping.Resource)
		if r.Mapping.Scope.Name() == meta.RESTScopeNameNamespace {
			// Namespaced resources.
			dr = dr.Namespace(obj.GetNamespace())
		}
```

2021-01-09 00:51 UTC, mook-as commented on pkg/minibroker/minibroker.go
> +			return fmt.Errorf("failed to get services: no services found")
I thought we needed to return the OSB-specific errors because the framework handle them specially?

2022-01-19 05:28 UTC, f0rmiga commented
/remove-lifecycle rotten

2022-05-06 14:35 UTC, mrbobbytables commented
This project is being archived, closing open issues and PRs.
Please see this PR for more information: https://github.com/kubernetes/community/pull/6632

2022-05-06 14:35 UTC, closed without merging